name: our_lists
description: The new Flutter application.

version: 0.0.5+5

environment:
  sdk: ^2.12.0

dependencies:
  flutter:
    sdk: flutter

  provider: 5.0.0
  firebase_core: 1.2.0
  cloud_firestore: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
