name: our_lists
description: The new Flutter application.

version: 0.0.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.5.0-dev.1"
  cloud_firestore: "0.14.0-dev.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
